import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:project_four_flutter/model/bloc_cubit/music_bloc.dart';

class DataBloc extends Cubit<MusicBloc> {
  DataBloc({MusicBloc state})
      : super(
          state = MusicBloc(
            photo: [
              'images/album_classica.jpg',
              'images/album_jazz.jpg',
              'images/album_opera.jpg',
              'images/album_rock.jpg',
            ],
            nameAlbum: ['Pop', 'Jazz', 'Opera', 'Rock'],
            listMusicsPopName: [
              "Wonder",
              "Dynamite",
              "Holy",
              "Still Have Me",
              "Kings & Queens",
              "Midnight Sky",
              "Watermelon Sugar",
              "Be Like That",
              "Ice Cream",
              "Lovesick Girls",
              "What a Feeling",
              "Adore You",
            ],
            listMusicsPopAuthor: [
              "Shawn Mendes",
              "BTS",
              "Justin Bieber",
              "Demi Lovato",
              "Ava Max",
              "Miley Cyrus",
              "Harry Styles",
              "Kane Brown, Swate Lee, Khalid",
              "Selena Gomez",
              "BLACKPINK",
              "One Direction",
              "Harry Styles",
            ],
            listMusicsJazzName: [
              "So What",
              "Fly Me To The Moon",
              "Mood Indigo",
              "Take Five",
              "The Girl From Ipanema",
              "Minnie The Moocher",
              "What A Wonderful World",
              "Strange Fruit",
              "Georgia On My Mind",
              "My Baby Just Cares For Me",
            ],
            listMusicsJazzAuthor: [
              "Miles Davis",
              "Frank Sinatra",
              "Duke Ellington & His Famous Orchestra",
              "Dave Brubeck Quartet",
              "Stan Getz & Joao Gilberto",
              "Cab Calloway",
              "Louis Armstrong",
              "Billie Holiday",
              "Ray Charles",
              "Nina Simone",
            ],
            listMusicsOperaName: [
              "Eine kleine Nachtmusik",
              "Fur Elise",
              "The Four Seasons",
              "Carmen",
              "Bolero",
              "Nessum Dorma",
            ],
            listMusicsOperaAuthor: [
              "Mozart",
              "Beethoven",
              "Vivaldi",
              "Bizet",
              "Ravel",
              "Puccini",
            ],
            listMusicsRockName: [
              "Sweet Emotion",
              "Kashmir",
              "Gimme Shelter",
              "A day in the Life",
              "Bohemian Rhapsody",
              "Everybody Wants Some!!",
              "Comfortably Numb",
              "Paranoid",
            ],
            listMusicsRockAuthor: [
              "Aerosmith",
              "Led Zeppelin",
              "Rolling Stones",
              "The Beatles",
              "Queen",
              "Van Halen",
              "Pink Floyd",
              "Black Sabbath",
            ],
          ),
        );
}
